/*
Even Fibanocci numbers
----------------------

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, 
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
    Ans::: 4613732
*/


/*
!First try: Loop way

#include<stdio.h>
#define N 4000000
int main(){
    int c, i = 0, a = 1, b = 2;
    int sum = b;
    while(a + b < N){
        c = a + b;
        if (i % 2 == 0)   a = c;
        else b = c;

        if(c % 2 == 0)     sum += c;
        
        i++;
    }
    printf("the sum is %d\n", sum );
}
*/


/*
!!//New way to do the same problem little bit advanced and little more brainstroming and clean
#include<stdio.h>
#define N 4000000
int main(){
    int a=1,b=2;
    int sum=b;
    while(a+b<N){
        b=a+b;
        a=b-a;

        if(b%2==0)   sum+=b;
    }
    printf("The sum is %d\n",sum);
}
*/


/*
!Math way 
but i haven't seen the algo yet, i just saw somewhere slightly that after every two 
number even fibo repeats
After: This is worst program i have made introducing another variable and making program cumbersome
#include<stdio.h>

#define N 4000000

int main(){
    int c,a=1, b=2;
    int i=0,j=0,sum=b;
    while(a+b<N){
        c=a+b;
        if (i%2==0) a=c;
        else b=c;

        if ( j == 2 ){
            printf("%d\n",c);
            sum+=c;
            j=0;
        }else{
            j++;
        }
        i++;
    }
    printf("the sum is %d\n",sum);
}
*/

//!using the formula 
/*
    Credit: Geeks for geeks
    We use the formula to determine the nth term in fibonnaci series
        Fn = {[(√5 + 1)/2] ^ n} / √5 
    http://www.maths.surrey.ac.uk/hosted-sites/R.Knott/Fibonacci/fibFormula.html 
    And we know that after 2 element even number appears so we can use this knowledge to our benefits
    !This is by far the best algo i found

*/

#include<stdio.h>
#include<math.h>
#define N 4000000
int nFibo(int n){
    double Phi=(sqrt(5)+1)/2;
    return round(pow(Phi,n)/sqrt(5));    
}

int main(){
    int sum = 0,fibo = 0;

    for(int i = 3; fibo < N ; i=i+3){
        fibo=nFibo(i);
        sum+=fibo;
    }
    sum-=fibo;
    printf("the sum is %d\n",sum);
}